### ISSUE TITLE
Any file or folder name on the executed file path cannot contain space or some symbols(win8 & 1.4.0)

### ISSUE THREAD

**Issue by chensivan** [sikuli/sikuli-slides#15]
If I named the ppt file's name as "hello world" or "hello$world", no matter what kind of open method, it could not be executed with Sikuli Slides app. Same issue if I create a folder named "Sikuli Slides", and then put "helloworld.pptx" in this folder, the slides cannot be operated by sikuli slides app.

I accidentally found this issue when I have a copy of my original "helloworld.pptx" file, and its name is automatically created as "helloworld (1).pptx", since there is space in the name, it came across the issue described above.

**Comment by doubleshow** [comment]
the new GUI accepts filenames with spaces.

**Comment by whalen-enterprises** [comment]
I am still having this problem with Sikuli Slides 1.5 on Mac OS. If I try to execute a PowerPoint slide using the command line and the path has a space in it I get the following:

$ java -jar sikuli-slides-1.5.0_macosx-x86_64.jar execute /Users/Test/Desktop/open\ sikuli\ website.pptx 
0    [main] DEBUG org.sikuli.slides.api.Slides  - execute slides with context Context{minScore=0.7, parameter={}, screenRegion=DesktopScreenRegion{screen=DesktopScreen{id=0}, x=0, y=0, width=1440, height=900, score=0.0}}
4    [main] ERROR org.sikuli.slides.api.io.PPTXBundle  - File does not exist: /Users/Test/Desktop/open%20sikuli%20website.pptx
Execution failed because java.io.IOException

So it looks to me like this problem still exists in the 1.5 code.
